name: 🐞 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug"]
assignees: []
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: What went wrong?
          placeholder: Describe the issue clearly
      validations:
          required: true

    - type: textarea
      id: steps
      attributes:
          label: Steps to Reproduce
          placeholder: |
              1. Go to ...
              2. Click on ...
              3. See error
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: Expected Behavior
          placeholder: What did you expect to happen?
      validations:
          required: true

    - type: input
      id: environment
      attributes:
          label: Environment
          placeholder: Browser / OS / Branch
